INSERT INTO `libros` (`titulo`, `autor`, `editorial`, `fecha_insercion`, `url_imagen`, `unidades` ,`borrado_virtual`) VALUES
('El fin de la eternidad', 'Isaac Asimov', 'Best Seller', NOW(), './img/el-fin-de-la-eternidad.jpg', NULL , NULL),
('Preludio a la fundación', 'Isaac Asimov', 'Best Seller', NOW(), './img/preludio-a-la-fundacion.jpg', NULL , NULL),
('Yo, Robot', 'Isaac Asimov', 'Best Seller', NOW(), './img/yo-robot.jpg', NULL , NULL),
('Bobedas de acero', 'Isaac Asimov', 'Best Seller', NOW(), './img/bobedas-de-acero.jpg', NULL , NULL),
('El sol desnudo', 'Isaac Asimov', 'Best Seller', NOW(), './img/el-sol-desnudo.jpg', NULL , NULL),
('Los robots del amanecer', 'Isaac Asimov', 'Best Seller', NOW(), './img/los-robots-del-amanecer.jpg', NULL , NULL),
('Robots e Imperio', 'Isaac Asimov', 'Best Seller', NOW(), './img/robots-e-imperio.jpg', NULL , NULL),
('En la arena estelar', 'Isaac Asimov', 'Best Seller', NOW(), './img/en-la-arena-estelar.jpg', NULL , NULL),
('Las corrientes del espacio', 'Isaac Asimov', 'Best Seller', NOW(), './img/las-corrientes-del-espacio.jpg', NULL , NULL),
( 'Un guijarro en el cielo', 'Isaac Asimov', 'Best Seller', NOW(), './img/un-guijarro-en-el-cielo.jpg', NULL , NULL),
( 'Hacia la fundacion', 'Isaac Asimov', 'Best Seller', NOW(), './img/hacia-la-fundacion.jpg', NULL , NULL),
( 'Fundación', 'Isaac Asimov', 'Best Seller', NOW(), './img/fundacion.jpg', NULL , NULL),
( 'Fundación e Imperio', 'Isaac Asimov', 'Best Seller', NOW(), './img/fundacion-e-imperio.jpg', NULL , NULL),
( 'Segunda Fundación', 'Isaac Asimov', 'Best Seller', NOW(), './img/segunda-fundacion.jpg', NULL , NULL),
( 'Los limites de la fundacion', 'Isaac Asimov', 'Best Seller', NOW(), './img/los-limites-de-la-fundacion.jpg', NULL , NULL),
( 'Fundacion y tierra', 'Isaac Asimov', 'Best Seller', NOW(), './img/fundacion-y-tierra.jfif', NULL , NULL),
( 'Amanecer rojo', 'Pierce Brown', 'RBA', NOW(), './img/amanecer-rojo.jpg', NULL , NULL),
( 'Hijo dorado', 'Pierce Brown', 'RBA', NOW(), './img/hijo-dorado.jpg', NULL , NULL),
( 'Mañana azul', 'Pierce Brown', 'RBA', NOW(), './img/manana-azul.jpg', NULL , NULL),
( 'Oro y ceniza', 'Pierce Brown', 'RBA', NOW(), './img/oro-y-ceniza.jpg', NULL , NULL),
( 'En las montañas de la locura', 'H.P. Lovecraft', 'Minotauro', NOW(), './img/en-las-montanas-de-la-locura.jpg', NULL , NULL),
( '1984', 'George Orwell', 'RBA', NOW(), './img/1984.jpg', NULL , NULL),
( 'Dune', 'Frank Herberts', 'Debolsillo', NOW(), './img/dune.jpg', NULL , NULL),
( 'Guía del autoestopista galáctico', 'Douglas Adams', 'Anagrama', NOW(), './img/guia-del-autoestopista-galactico.jpg', NULL , NULL),
( 'El problema de los tres cuerpos', 'Liu Cixin', 'RBA', NOW(), './img/el-problema-de-los-tres-cuerpos.jpg', NULL , NULL),
( 'ILLUMINAE. Expediente_01', 'Amie Kaufman', 'ALFAGUARA', NOW(), './img/illuminae.jpg', NULL , NULL),
( 'GEMINA. Expediente_02', 'Amie Kaufman', 'Oneworld tions', NOW(), './img/gemina.jpg', NULL , NULL),
( 'OBSIDIO. Expediente_03', 'Amie Kaufman', 'Oneworld tions', NOW(), './img/obsidio.jpg', NULL , NULL);